### ISSUE TITLE
Slight discrepancy between 'quick edit' select field options, and 'post edit' select field

### ISSUE THREAD

**Issue by smarterdigitalltd** [JJJ/post-type-switcher#10]
Hello!

I am a plugin developer who uses a non-public CPT inside my plugin.

If you edit a post inside my CPT, the Post Type Switcher select field displays a list of post types INCLUDING my CPT: https://cl.ly/2G2Z2x3p423q

If, however, you 'quick edit' the same CPT, the Post Type Switcher select field displays a list of post types EXCLUDING my CPT: https://cl.ly/35260N0e2G2G

This means that if a user uses 'quick edit' for anything at all on my CPT, the post type will be switched.

For now, I will try and unhook the select field from the quick edit screen, but perhaps something to check?

Thanks :-)

**Comment by JJJ** [comment]
Confirmed.

**Comment by JJJ** [comment]
Hey there @smarterdigitalltd, is this still an issue?

(I may have fixed it without referencing this issue.)
