### ISSUE TITLE
Preference on Gutenberg compatibility?

### ISSUE THREAD

**Issue by danielbachhuber** [JJJ/post-type-switcher#11]
Hi 👋 

I'd like to contribute Gutenberg compatibility to this plugin. There are a couple of paths I could see this taking:

**1. Recreate similar `<select>` UI in the Status & Visibility Panel (medium LOE)**

<img width="434" alt="image" src="https://user-images.githubusercontent.com/36432/55030428-9185da00-4fc9-11e9-87e3-341d0bdb0d04.png">

* The available post types to switch to would be loaded into Gutenberg via `wp_localize_script()`.
* We'd need to have some discussion on how to adapt the existing UX to a more Gutenberg-native UX.
* When the user selects a different post type, they'd be hard-refreshed to that new edit URL (because the new post type may or may not use Gutenberg, etc.).

**2. Load the existing UI into a side meta box (small LOE)**

<img width="358" alt="image" src="https://user-images.githubusercontent.com/36432/55030168-00166800-4fc9-11e9-8f23-e9b2efbd67c2.png">

* Register a meta box that only loads in the block editor.
* Reuses existing code and UI.
---

Any preference on which approach I take? Other aspects I should be considering?

My personal preference would be 2, given:
* Reuses existing code.
* Lower level of effort.
* Position indicates switching post types is an infrequent task, not something in the normal publishing flow.

**Comment by JJJ** [comment]
Hey Daniel! Awesome!

Personally, I think 1 feels best in the context of it being a primary Document property.

I do agree with it being an infrequent task for most users, but because it’s an essential property of every post object, it’s always felt like it belonged with the others — more _important_ than tags or categories, even if it’s not a frequent user interaction.

As a compromise, is it possible to wedge a PTS meta-box under categories?

Unrelated, I posted some other concerns in a sticky topic in the forums: https://wordpress.org/support/topic/wordpress-5-0-support-coming-soon/

Specifically, how should we handle switching between post types that do or don’t support the block based editor?

I don’t like AYS prompts. But I want to make sure users don’t get their content mangled by WordPress by switching back or forth.

**Comment by danielbachhuber** [comment]
> Personally, I think 1 feels best in the context of it being a primary Document property.

Yep, seems reasonable. Do you have preferred UI for it?

> As a compromise, is it possible to wedge a PTS meta-box under categories?

I don't believe it's possible to add UI elsewhere on that panel, unless something has changed recently. 

> Specifically, how should we handle switching between post types that do or don’t support the block based editor?

I'm not sure this is a concern, actually. Like the existing behavior, changing the value would perform a _full_ redirect and page refresh. This is necessary because different post types can have different meta boxes, some post types don't have `show_in_rest=true` and don't support the block editor, etc.

> Edit: If we go the 2 route, that gives us more room to add any possible warnings regarding editor support?

Not sure I follow. What warnings would be necessary?

**Comment by JJJ** [comment]
Let’s say a user switches from a type that supports blocks, to a type that doesn’t.

What happens to their blocks when they try to edit it? Can they make edits and switch back to a type that supports blocks without losing any data (and reverse?)

**Comment by danielbachhuber** [comment]
> What happens to their blocks when they try to edit it? Can they make edits and switch back to a type that supports blocks without losing any data (and reverse?)

I think they'd see this message: https://github.com/WordPress/gutenberg/pull/8247

Via https://github.com/WordPress/gutenberg/issues/8213

Technically, yes, they could make edits and then switch back to a type that supports blocks. If they were making edits to the block content, then YMMV on whether they end up as valid edits.

@bph Any concerns on your end in this context?

**Comment by bph** [comment]
My instincts tells me to go with option 1, the one reason as that's where people who used it before will expect it. There is enough re-discovery going on with the switch to the block editor that a "Good, that's hasn't changed" experience is a relief<g> 

The warning when switching between a post type using block editor to classic editor has been solved and should kick once the new post type admin screen is loaded. 

Loosing content was not a concern of the plugin prior to the block editor though. It was pretty clear that one looses categories and tags or content in meta-boxes. A decision to switch the post type, is a very deliberate one, and the plugin is a tool to execute on it as seamless as possible. That's the one thing is does well.

**Comment by JJJ** [comment]
Thanks @bph for the feedback, and thanks to @danielbachhuber this is fully realized and merged into the master branch!

Can you give it a quick look? It seems great to me, and the more testing the better.

**Comment by danielbachhuber** [comment]
@JJJ Still planning to release this?

**Comment by JJJ** [comment]
@danielbachhuber releasing today 🥳
