### ISSUE TITLE
Don’t show post type admin column by default

### ISSUE THREAD

**Issue by tedw** [JJJ/post-type-switcher#20]
Hi there, I was wondering if it would be possible to not show the “Type” column in the admin by default:

https://github.com/JJJ/post-type-switcher/blob/70fefda795c54e776d566de39d83179a4b225523/post-type-switcher.php#L162-L171

I prefer to manage my admin columns manually, or by using other plugins specifically for managing admin columns. Also, having a post type column doesn’t seem particularly useful in my experience since it’s the same for every post in the listing.

Anyway, thanks for your work on this plugin! It definitely made things easier for me on a recent client project.

**Comment by tedw** [comment]
In case anyone else wants to know how to remove the column manually, here’s one way to do it:

```php
foreach ( ['page', 'post', 'custom_post_type_1', 'custom_post_type_2'] as $name ) {
    add_filter( "manage_{$name}_posts_columns", function( $columns ) {
        unset($columns['post_type']);
        return $columns;
    }, 20, 1);
}
```

**Comment by JJJ** [comment]
Hey @tedw. I think this is a good suggestion. I'll look into this soon.

**Comment by Inwerpsel** [comment]
There's also the [default_hidden_columns](https://developer.wordpress.org/reference/hooks/default_hidden_columns/) filter.
```php
add_filter( 'default_hidden_columns', function ( $hidden ) {
	$hidden[] = 'post_type';

	return $hidden;
}, 10, 1);
