### ISSUE TITLE
Interaction with Advanced Custom Fields required fields

### ISSUE THREAD

**Issue by MadtownLems** [JJJ/post-type-switcher#25]
Situation:
I have stock core Posts, and I have a CPT called "Articles" that uses Advanced Custom Fields to have some required fields, such as the Featured Image.

If I use Post Type Switcher to switch a Post to an Article, I can do that (even if the post doesn't have a Featured Image).
If I try to switch the featured-image-less Article back to a Post, I can't (because the Update is blocked by client-side checking for a required Featured Image, even though that wouldn't be required once I complete the switch).

While I really don't expect you to address either of these oddities, I figured I'd raise it just so you're aware and in the random chance you or someone else does want to try to address it. Cheers!

**Comment by JJJ** [comment]
Hey @MadtownLems 🙌 thanks for bringing this to my attention here.

Apologies for letting this issue go unanswered.

I'll do some testing soon and make some improvements. It's the first I've heard of updates failing because of unsupported features between the types, and is an unexpected problem 🗡️ 🤣

**Comment by JJJ** [comment]
I finally reproduced this, and I see what you mean.

I'm comfortable leaving this as-is, at least for the time being.

If we/anyone wants to improve this later, let's do it then!
