### ISSUE TITLE
Conflict with metabox when inserting posts on post save

### ISSUE THREAD

**Issue by TimothyBJacobs** [JJJ/post-type-switcher#7]
We have a meta box on a custom post type. The user performs a number of actions in the meta box which sets up input fields to be sent to `post.php`. When we process our custom form data, we iterate over those input fields and create posts of _another_ custom post type.

Because the post type switcher in a meta box doesn't have the "No Change" option and the select defaults to the current post's post type, it results in inserting posts of the current post type, not the desired post type because Post Type Switcher's data is still in `$_REQUEST`. 

Happy to submit a patch if desired.

**Comment by JJJ** [comment]
Hey @TimothyBJacobs! 👋 If you're able to share the plugin you're using to save nested posts, that will help me troubleshoot this further.

**Comment by TimothyBJacobs** [comment]
Hey @JJJ! I think this was probably iThemes Exchange or some related add-on. But I couldn't tell you for sure. I'll try and write up an example.

**Comment by JJJ** [comment]
@TimothyBJacobs (or anyone else) please feel free to reopen this issue as needed ❤️
