### ISSUE TITLE
attachments get changed to post

### ISSUE THREAD

**Issue by maartenbusstra** [JJJ/post-type-switcher#8]
We're having issues with ACF-fields containing images being changed from `attachment` to `post`, when doing a regular save with newly added / modified images in those fields. I thought this might be related to #5. Do you think you could have a look?

We're on 3.0.0.

**Comment by 1ucay** [comment]
Hi, replace function in post-type-switcher.php


	public function override_type( $data = array(), $postarr = array() ) {

		// Bail if form field is missing
		if ( empty( $_REQUEST['pts_post_type'] ) || empty( $_REQUEST['pts-nonce-select'] ) ) {
			return $data;
		}

		// Post type information
		$post_type        = sanitize_key( $_REQUEST['pts_post_type'] );
		$post_type_object = get_post_type_object( $post_type );

		// Bail if empty post type
		if ( empty( $post_type ) || empty( $post_type_object ) ) {
			return $data;
		}

		global $post;
		if ( !empty( $post ) && $post->ID !== $postarr['ID'] ) {
			return $data;
		}

		// Bail if user cannot 'edit_post'
		if ( ! current_user_can( 'edit_post', $postarr['ID'] ) ) {
			return $data;
		}

		// Bail if nonce is invalid
		if ( ! wp_verify_nonce( $_REQUEST['pts-nonce-select'], 'post-type-selector' ) ) {
			return $data;
		}

		// Bail if autosave
		if ( wp_is_post_autosave( $postarr['ID'] ) ) {
			return $data;
		}

		// Bail if revision
		if ( wp_is_post_revision( $postarr['ID'] ) ) {
			return $data;
		}

		// Bail if it's a revision
		if ( in_array( $postarr['post_type'], array( $post_type, 'revision' ), true ) ) {
			return $data;
		}

		// Bail if user cannot 'publish_posts' on the new type
		if ( ! current_user_can( $post_type_object->cap->publish_posts ) ) {
			return $data;
		}

		// Update post type
		$data['post_type'] = $post_type;

		// Return modified post data
		return $data;
	}

**Comment by JJJ** [comment]
Might be related to #7.

**Comment by JJJ** [comment]
Switching to attachments has been disabled since 3.0.0, so this conflict has been worked-around for a while.

If/when that gets re-enabled, this will need to be revisited.
